//! Deterministic Rust regression generation from verified replay bundles.

use crate::{DifferentialVerdict, ReplayRequest, ReplayRequestError};

/// Render a self-contained AIRLock regression test for one exact replay request.
///
/// The generated test depends on `airlock-stwo` and `serde_json`, embeds no
/// filesystem paths, and asserts the exact differential verdict captured by the
/// verified replay bundle.
pub fn generate_regression_source(
    request: &ReplayRequest,
    expected: DifferentialVerdict,
) -> Result<String, ReplayRequestError> {
    request.validate()?;
    let request_json = serde_json::to_string(request)
        .map_err(|error| ReplayRequestError::Serialization(error.to_string()))?;
    let request_literal = format!("{request_json:?}");
    let expected_variant = format!("{expected:?}");

    Ok(format!(
        r#"// Generated by AIRLock from a pinned replay request.
use airlock_stwo::{{execute_replay_request, DifferentialVerdict, ReplayRequest}};

#[test]
fn airlock_stwo_replay_regression() {{
    let request: ReplayRequest = serde_json::from_str({request_literal})
        .expect("embedded AIRLock replay request");
    let replay = execute_replay_request(&request).expect("pinned Stwo replay");
    assert_eq!(replay.verdict, DifferentialVerdict::{expected_variant});
}}
"#
    ))
}

#[cfg(test)]
mod tests {
    use airlock_boundary::{MutationOperation, ScalarMutation};

    use crate::StwoBoundaryAdapter;

    use super::*;

    #[test]
    fn generated_regression_is_deterministic_and_path_independent() {
        let adapter = StwoBoundaryAdapter::new().expect("adapter");
        let request = ReplayRequest::mutation(
            "generated-regression",
            vec![MutationOperation::ReplaceScalar {
                path: adapter
                    .first_sampled_value_path()
                    .expect("sampled-value path"),
                value: ScalarMutation::Increment,
            }],
        );
        let first = generate_regression_source(&request, DifferentialVerdict::MutationRejected)
            .expect("regression source");
        let second = generate_regression_source(&request, DifferentialVerdict::MutationRejected)
            .expect("regression source");

        assert_eq!(first, second);
        assert!(first.contains("DifferentialVerdict::MutationRejected"));
        assert!(first.contains("generated-regression"));
        assert!(!first.contains("/Users/"));
    }
}
