//! Boundary contracts and observations.

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::{BoundaryPath, MutationPlan};

/// Stable schema identifier for verifier-boundary contracts.
pub const BOUNDARY_SCHEMA_ID: &str = "airlock.boundary-contract";

/// Serialized boundary-contract version.
pub const BOUNDARY_SCHEMA_VERSION: &str = "0.1.0";

/// A cardinality measured at one proof path.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CountAtPath {
    /// Container path.
    pub path: BoundaryPath,
    /// Number of entries in that container.
    pub count: usize,
}

impl CountAtPath {
    /// Construct a cardinality observation.
    pub fn new(path: BoundaryPath, count: usize) -> Self {
        Self { path, count }
    }
}

/// Verifier-derived shape contract for one proof target.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BoundaryContract {
    /// Schema identity.
    pub schema: String,
    /// Schema version.
    pub schema_version: String,
    /// Stable target name.
    pub target: String,
    /// Exact upstream source identifier or commit.
    pub upstream_commit: String,
    /// Cardinalities derived independently from the verifier request.
    pub requested: Vec<CountAtPath>,
}

impl BoundaryContract {
    /// Construct a contract with the current schema identity.
    pub fn new(
        target: impl Into<String>,
        upstream_commit: impl Into<String>,
        requested: Vec<CountAtPath>,
    ) -> Self {
        Self {
            schema: BOUNDARY_SCHEMA_ID.to_owned(),
            schema_version: BOUNDARY_SCHEMA_VERSION.to_owned(),
            target: target.into(),
            upstream_commit: upstream_commit.into(),
            requested,
        }
    }

    /// Validate the contract before it is used as an oracle.
    pub fn validate(&self) -> Result<(), BoundaryContractError> {
        if self.schema != BOUNDARY_SCHEMA_ID || self.schema_version != BOUNDARY_SCHEMA_VERSION {
            return Err(BoundaryContractError::WrongSchema {
                schema: self.schema.clone(),
                version: self.schema_version.clone(),
            });
        }
        if self.target.trim().is_empty() {
            return Err(BoundaryContractError::EmptyTarget);
        }
        if self.upstream_commit.trim().is_empty() {
            return Err(BoundaryContractError::EmptyUpstreamCommit);
        }
        validate_counts(&self.requested, "requested")?;
        if self.requested.is_empty() {
            return Err(BoundaryContractError::EmptyRequest);
        }
        Ok(())
    }
}

/// Whether a run is the honest seed or an adversarial mutation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
pub enum CaseKind {
    /// Unmodified proof generated by the honest prover.
    Honest,
    /// Proof changed according to a recorded mutation plan.
    Mutated,
}

/// Coarse verifier outcome used by generic boundary oracles.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "snake_case", deny_unknown_fields)]
pub enum VerificationOutcome {
    /// Verification returned success.
    Accepted,
    /// Verification returned a typed rejection.
    Rejected {
        /// Stable rejection category where available.
        kind: String,
        /// Diagnostic message.
        message: String,
    },
    /// Verification unwound or the subprocess aborted.
    Panicked {
        /// Captured panic or process diagnostic.
        message: String,
    },
    /// The configured time budget expired.
    TimedOut,
    /// The adapter cannot model this target or proof shape.
    Unsupported {
        /// Why the target is unsupported.
        reason: String,
    },
}

impl VerificationOutcome {
    /// Return the outcome class without diagnostics.
    pub const fn class(&self) -> OutcomeClass {
        match self {
            Self::Accepted => OutcomeClass::Accept,
            Self::Rejected { .. } => OutcomeClass::Reject,
            Self::Panicked { .. } => OutcomeClass::Panic,
            Self::TimedOut => OutcomeClass::Timeout,
            Self::Unsupported { .. } => OutcomeClass::Unsupported,
        }
    }
}

/// Diagnostic-free verifier outcome class.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE", deny_unknown_fields)]
pub enum OutcomeClass {
    /// Accepted.
    Accept,
    /// Rejected with a typed error.
    Reject,
    /// Panicked or aborted.
    Panic,
    /// Timed out.
    Timeout,
    /// Unsupported by the adapter.
    Unsupported,
}

/// One observed verifier execution.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BoundaryObservation {
    /// Stable target name copied from the contract used to create this run.
    pub target: String,
    /// Exact upstream source identifier or commit exercised by this run.
    pub upstream_commit: String,
    /// Stable test-case identifier.
    pub case_id: String,
    /// Verifier layer, such as `raw_pcs` or `framework`.
    pub layer: String,
    /// Honest or mutated run.
    pub case_kind: CaseKind,
    /// Structured mutation applied to the honest seed, when any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mutation: Option<MutationPlan>,
    /// Cardinalities actually supplied by the proof.
    pub supplied: Vec<CountAtPath>,
    /// Cardinalities consumed by the verifier relation.
    pub consumed: Vec<CountAtPath>,
    /// Final verifier outcome.
    pub outcome: VerificationOutcome,
}

impl BoundaryObservation {
    /// Validate observation metadata independently of its verifier result.
    pub fn validate(&self) -> Result<(), BoundaryContractError> {
        if self.target.trim().is_empty() {
            return Err(BoundaryContractError::EmptyTarget);
        }
        if self.upstream_commit.trim().is_empty() {
            return Err(BoundaryContractError::EmptyUpstreamCommit);
        }
        if self.case_id.trim().is_empty() {
            return Err(BoundaryContractError::EmptyCaseId);
        }
        if self.layer.trim().is_empty() {
            return Err(BoundaryContractError::EmptyLayer);
        }
        validate_counts(&self.supplied, "supplied")?;
        validate_counts(&self.consumed, "consumed")?;
        if let VerificationOutcome::Rejected { kind, .. } = &self.outcome
            && !is_valid_rejection_kind(kind)
        {
            return Err(BoundaryContractError::InvalidRejectionKind(kind.clone()));
        }
        match (self.case_kind, &self.mutation) {
            (CaseKind::Honest, Some(_)) => {
                return Err(BoundaryContractError::UnexpectedMutationForHonestCase);
            }
            (CaseKind::Mutated, None) => {
                return Err(BoundaryContractError::MissingMutationForMutatedCase);
            }
            (_, Some(plan)) => plan.validate().map_err(BoundaryContractError::Mutation)?,
            _ => {}
        }
        Ok(())
    }
}

fn is_valid_rejection_kind(kind: &str) -> bool {
    !kind.is_empty()
        && kind.trim() == kind
        && kind.bytes().all(|byte| {
            byte.is_ascii_lowercase()
                || byte.is_ascii_digit()
                || matches!(byte, b'_' | b'-' | b'.' | b':')
        })
}

fn validate_counts(counts: &[CountAtPath], set: &'static str) -> Result<(), BoundaryContractError> {
    let mut paths = BTreeSet::new();
    for entry in counts {
        if !entry.path.is_valid() {
            return Err(BoundaryContractError::EmptyPath { set });
        }
        if !paths.insert(entry.path.clone()) {
            return Err(BoundaryContractError::DuplicatePath {
                set,
                path: entry.path.clone(),
            });
        }
    }
    Ok(())
}

/// Invalid boundary artifacts cannot produce a green result.
#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum BoundaryContractError {
    /// Unknown schema identity or version.
    #[error("unexpected boundary schema `{schema}` version `{version}`")]
    WrongSchema {
        /// Supplied schema.
        schema: String,
        /// Supplied version.
        version: String,
    },
    /// Target name is empty.
    #[error("boundary target must not be empty")]
    EmptyTarget,
    /// Upstream source identity is empty.
    #[error("upstream commit must not be empty")]
    EmptyUpstreamCommit,
    /// A request contract with no measured paths cannot establish consumption.
    #[error("boundary request must contain at least one measured path")]
    EmptyRequest,
    /// Case id is empty.
    #[error("boundary case id must not be empty")]
    EmptyCaseId,
    /// Layer id is empty.
    #[error("boundary layer must not be empty")]
    EmptyLayer,
    /// A proof-field path is empty.
    #[error("{set} count contains an empty proof-field path")]
    EmptyPath {
        /// Cardinality set.
        set: &'static str,
    },
    /// A path appears twice in one cardinality set.
    #[error("duplicate {set} count for path {path:?}")]
    DuplicatePath {
        /// Cardinality set.
        set: &'static str,
        /// Duplicated path.
        path: BoundaryPath,
    },
    /// Honest cases must be unmodified.
    #[error("honest boundary case unexpectedly contains a mutation plan")]
    UnexpectedMutationForHonestCase,
    /// Mutated cases require a replayable mutation plan.
    #[error("mutated boundary case is missing its mutation plan")]
    MissingMutationForMutatedCase,
    /// Typed rejections require a stable canonical category.
    #[error("invalid rejection category `{0}`")]
    InvalidRejectionKind(String),
    /// Observation target does not match its request contract.
    #[error("observation target `{observed}` does not match contract target `{expected}`")]
    TargetMismatch {
        /// Contract target.
        expected: String,
        /// Observed target.
        observed: String,
    },
    /// Observation source does not match its request contract.
    #[error("observation upstream commit `{observed}` does not match contract commit `{expected}`")]
    UpstreamCommitMismatch {
        /// Contract source identity.
        expected: String,
        /// Observed source identity.
        observed: String,
    },
    /// The mutation plan is malformed.
    #[error(transparent)]
    Mutation(#[from] crate::MutationPlanError),
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{MutationOperation, MutationPlan};

    fn path() -> BoundaryPath {
        BoundaryPath::new("proof", vec![0, 1])
    }

    #[test]
    fn contract_rejects_duplicate_paths() {
        let count = CountAtPath::new(path(), 2);
        let contract = BoundaryContract::new("target", "commit", vec![count.clone(), count]);
        assert!(matches!(
            contract.validate(),
            Err(BoundaryContractError::DuplicatePath {
                set: "requested",
                ..
            })
        ));
    }

    #[test]
    fn observation_kind_and_mutation_must_agree() {
        let observation = BoundaryObservation {
            target: "target".to_owned(),
            upstream_commit: "commit".to_owned(),
            case_id: "honest".to_owned(),
            layer: "raw".to_owned(),
            case_kind: CaseKind::Honest,
            mutation: Some(MutationPlan {
                seed_id: "seed".to_owned(),
                seed_artifact_sha256: "11".repeat(32),
                mutated_artifact_sha256: "22".repeat(32),
                operations: vec![MutationOperation::Drop {
                    path: path(),
                    index: 0,
                }],
            }),
            supplied: vec![],
            consumed: vec![],
            outcome: VerificationOutcome::Accepted,
        };
        assert_eq!(
            observation.validate(),
            Err(BoundaryContractError::UnexpectedMutationForHonestCase)
        );
    }

    #[test]
    fn unknown_serialized_fields_are_rejected() {
        let json = r#"{
            "schema":"airlock.boundary-contract",
            "schema_version":"0.1.0",
            "target":"target",
            "upstream_commit":"commit",
            "requested":[{"path":{"field":"proof","indices":[]},"count":1}],
            "typo_field":true
        }"#;
        let error = serde_json::from_str::<BoundaryContract>(json).expect_err("unknown field");
        assert!(error.to_string().contains("unknown field"));
    }
}
